url: "https://eoagoldsolo.com"
defaults:
  -
    scope:
      path: "pinterest-5067a.html"
    values:
      sitemap: false
  -
    scope:
      path: "SECURITY.md"
    values:
      sitemap: false
  -
    scope:
      path: "blog/*.html"
    values:
      sitemap: false
  -
    scope:
      path: "docs/fav/"
    values:
      sitemap: false
  -
    scope:
      path: "docs/img/svg/"
    values:
      sitemap: false
plugins:
    - jekyll-sitemap
    - jekyll-feed
title: EOA GOLD SOLO RAYA | WA 08567712818
description: Agent of Gold resmi dari EOA GOLD di Solo Raya. EOA GOLD adalah emas logam mulia yang dicetak kepingan mulai dari 0,1 gram hingga 5 gram.
url: "https://eoagoldsolo.com"
author:
    twitter: eoagoldsolo
