url: "https://eoagoldsolo.com"
plugins:
    - jekyll-sitemap
    - jekyll-feed
defaults:
    -
    scope:
      path: "/pinterest-5067a.html"
    values:
      sitemap: false
title: EOA GOLD SOLO RAYA | WA 08567712818
description: Agent of Gold resmi dari EOA GOLD di Solo Raya. EOA GOLD adalah emas logam mulia yang dicetak kepingan mulai dari 0,1 gram hingga 5 gram.
url: "https://eoagoldsolo.com"
author:
    twitter: eoagoldsolo
